import type { GameClass, MotionProfile } from './types';

/**
 * УСЛОВНЫЕ игровые классы. Коды и параметры вымышлены и подобраны для наглядной анимации и понятных
 * игровых решений. Они не являются характеристиками реальных самолётов, ракет или комплексов и не
 * получены из справочника. Историческое название, если пользователь его выбрал, служит только подписью.
 */

const aero = (p: Partial<MotionProfile> & Pick<MotionProfile, 'cruiseSpeed' | 'maxSpeed' | 'turnRate' | 'cruiseAlt'>): MotionProfile => ({
  type: 'aero',
  minSpeed: Math.round(p.cruiseSpeed * 0.45),
  accel: 6,
  climbRate: 40,
  sinkRate: 50,
  maxAlt: 15000,
  windFactor: 1,
  ...p,
});

export const GAME_CLASSES: GameClass[] = [
  {
    id: 'g-fighter',
    code: 'И-α',
    name: 'Условный истребитель-перехватчик',
    kind: 'fighter',
    airCategory: 'aircraft',
    motion: aero({ cruiseSpeed: 240, maxSpeed: 420, turnRate: 9, cruiseAlt: 8000, accel: 12, climbRate: 90 }),
    sensor: { rangeKm: 90, detectP: 0.55, classifyS: 12 },
    weapon: { projectile: 'g-air-missile', stock: 4, rangeKm: 35, cooldownS: 8, baseP: 0.6, compat: { aircraft: 1, uav: 0.9, cruise: 0.7 } },
    signature: 0.8,
    enduranceS: 2700,
    prepS: 180,
    description: 'Игровой профиль: быстрый манёвренный самолёт с условным датчиком и запасом условных авиационных ракет.',
  },
  {
    id: 'g-carrier',
    code: 'Н-β',
    name: 'Условный самолёт-носитель',
    kind: 'bomber',
    airCategory: 'aircraft',
    motion: aero({ cruiseSpeed: 210, maxSpeed: 260, turnRate: 3, cruiseAlt: 9000, accel: 3, climbRate: 20 }),
    signature: 1,
    enduranceS: 7200,
    prepS: 420,
    payloadClasses: ['g-cruise'],
    payloadMax: 6,
    description: 'Игровой профиль: медленно разворачивается, несёт условную нагрузку, которая отделяется один раз и дальше летит сама.',
  },
  {
    id: 'g-recon',
    code: 'Р-ε',
    name: 'Условный разведчик',
    kind: 'recon',
    airCategory: 'aircraft',
    motion: aero({ cruiseSpeed: 200, maxSpeed: 300, turnRate: 5, cruiseAlt: 11000, climbRate: 30 }),
    sensor: { rangeKm: 160, detectP: 0.7, classifyS: 8 },
    signature: 0.9,
    enduranceS: 9000,
    prepS: 300,
    description: 'Игровой профиль: дальний условный датчик, передаёт обстановку своей стороне; взаимодействий не выполняет.',
  },
  {
    id: 'g-support',
    code: 'В-κ',
    name: 'Условный транспортный самолёт',
    kind: 'support',
    airCategory: 'aircraft',
    motion: aero({ cruiseSpeed: 170, maxSpeed: 220, turnRate: 3, cruiseAlt: 7000, climbRate: 15 }),
    signature: 1,
    enduranceS: 10800,
    prepS: 360,
    description: 'Игровой профиль: вспомогательный борт для сценариев перелёта и демонстрации опознавания.',
  },
  {
    id: 'g-uav',
    code: 'Д-ζ',
    name: 'Условный беспилотный аппарат',
    kind: 'uav',
    airCategory: 'uav',
    motion: aero({ cruiseSpeed: 45, maxSpeed: 60, turnRate: 6, cruiseAlt: 3000, accel: 2, climbRate: 5, sinkRate: 6, maxAlt: 7000, windFactor: 1 }),
    sensor: { rangeKm: 40, detectP: 0.6, classifyS: 15 },
    signature: 0.35,
    enduranceS: 14400,
    prepS: 120,
    description: 'Игровой профиль: медленный малозаметный аппарат; сильнее всех сносится ветром.',
  },
  {
    id: 'g-cruise',
    code: 'К-γ',
    name: 'Условный крылатый объект',
    kind: 'cruise',
    airCategory: 'cruise',
    motion: aero({ cruiseSpeed: 230, maxSpeed: 250, turnRate: 4, cruiseAlt: 120, accel: 8, climbRate: 30, sinkRate: 60, maxAlt: 9000, windFactor: 1 }),
    signature: 0.4,
    enduranceS: 5400,
    description: 'Игровой профиль «самолёт-снаряд»: после отделения снижается до малой высоты и летит к условной области назначения.',
  },
  {
    id: 'g-ballistic',
    code: 'Б-δ',
    name: 'Условный баллистический объект',
    kind: 'ballistic',
    airCategory: 'ballistic',
    motion: { type: 'ballistic', cruiseSpeed: 1400, maxSpeed: 1400, minSpeed: 0, accel: 40, turnRate: 0, climbRate: 0, sinkRate: 0, cruiseAlt: 0, maxAlt: 90000, windFactor: 0, apexAlt: 60000, boostS: 35 },
    signature: 0.9,
    description: 'Игровой профиль: условная дуга для анимации. Это не расчёт баллистической траектории; ветер на профиль не влияет.',
  },
  {
    id: 'g-air-missile',
    code: 'А-η',
    name: 'Условная авиационная ракета',
    kind: 'air-missile',
    airCategory: 'missile',
    motion: aero({ cruiseSpeed: 700, maxSpeed: 800, turnRate: 25, cruiseAlt: 8000, accel: 60, climbRate: 250, sinkRate: 250, windFactor: 0 }),
    signature: 0.3,
    maxFlightS: 90,
    proximityKm: 1.2,
    description: 'Игровой снаряд истребителя. Следует к текущему положению цели (игровое преследование, не алгоритм наведения).',
  },
  {
    id: 'g-sam-missile',
    code: 'З-θм',
    name: 'Условная зенитная ракета',
    kind: 'sam-missile',
    airCategory: 'missile',
    motion: aero({ cruiseSpeed: 900, maxSpeed: 1000, turnRate: 20, cruiseAlt: 6000, accel: 80, climbRate: 400, sinkRate: 400, maxAlt: 30000, windFactor: 0 }),
    signature: 0.3,
    maxFlightS: 80,
    proximityKm: 1.5,
    description: 'Игровой снаряд зенитного поста. Следует к текущему положению цели; исход решает жребий по игровым правилам.',
  },
  {
    id: 'g-ad-post',
    code: 'З-θ',
    name: 'Условный зенитный пост (универсальный)',
    kind: 'ad-post',
    sensor: { rangeKm: 120, detectP: 0.6, classifyS: 10 },
    weapon: { projectile: 'g-sam-missile', stock: 6, rangeKm: 60, cooldownS: 6, baseP: 0.65, compat: { aircraft: 1, uav: 0.8, cruise: 0.75 } },
    signature: 0,
    description: 'Игровой профиль: работает по самолётам, беспилотникам и крылатым объектам. Баллистические объекты — вне совместимости класса.',
  },
  {
    id: 'g-ad-point',
    code: 'З-ι',
    name: 'Условный пост ближнего рубежа',
    kind: 'ad-post',
    sensor: { rangeKm: 50, detectP: 0.65, classifyS: 6 },
    weapon: { projectile: 'g-sam-missile', stock: 8, rangeKm: 18, cooldownS: 4, baseP: 0.6, compat: { cruise: 1, uav: 1, aircraft: 0.6 } },
    signature: 0,
    description: 'Игровой профиль: короткий рубеж, лучше всего совместим с крылатыми объектами и беспилотниками.',
  },
  {
    id: 'g-ad-upper',
    code: 'З-λ',
    name: 'Условный пост верхнего рубежа',
    kind: 'ad-post',
    sensor: { rangeKm: 250, detectP: 0.7, classifyS: 14 },
    weapon: { projectile: 'g-sam-missile', stock: 4, rangeKm: 120, cooldownS: 10, baseP: 0.55, compat: { ballistic: 0.8, aircraft: 0.7 } },
    signature: 0,
    description: 'Игровой профиль: единственный класс, совместимый с баллистической категорией; по крылатым объектам не работает.',
  },
  {
    id: 'g-radar',
    code: 'Н-ρ',
    name: 'Условный пост наблюдения',
    kind: 'radar',
    sensor: { rangeKm: 200, detectP: 0.65, classifyS: 10 },
    signature: 0,
    description: 'Игровой профиль: только наблюдение; обстановка передаётся всем постам своей стороны.',
  },
  {
    id: 'g-airfield',
    code: 'Аэ',
    name: 'Условный аэродром',
    kind: 'airfield',
    signature: 0,
    description: 'Точка базирования: сюда возвращаются самолёты своей стороны, если у них не задана другая база.',
  },
  {
    id: 'g-launcher',
    code: 'П-μ',
    name: 'Условная пусковая',
    kind: 'launcher',
    signature: 0,
    prepS: 60,
    payloadClasses: ['g-ballistic', 'g-cruise'],
    payloadMax: 4,
    description: 'Игровой профиль: в заданное время выпускает свою условную нагрузку к условной области назначения.',
  },
];

export const CLASS_BY_ID: Record<string, GameClass> = Object.fromEntries(GAME_CLASSES.map((c) => [c.id, c]));

/** Классы, которые пользователь размещает сам (снаряды появляются только как следствие действий). */
export const PLACEABLE = GAME_CLASSES.filter((c) => c.kind !== 'air-missile' && c.kind !== 'sam-missile' && c.kind !== 'cruise' && c.kind !== 'ballistic');

export const KIND_RU: Record<string, string> = {
  fighter: 'истребитель/перехватчик',
  bomber: 'носитель',
  recon: 'разведчик',
  support: 'вспомогательный',
  uav: 'беспилотник',
  cruise: 'крылатый объект',
  ballistic: 'баллистический объект',
  'air-missile': 'авиационная ракета',
  'sam-missile': 'зенитная ракета',
  'ad-post': 'зенитный пост',
  radar: 'пост наблюдения',
  airfield: 'аэродром',
  launcher: 'пусковая',
};

export const CATEGORY_RU: Record<string, string> = {
  aircraft: 'самолёт',
  uav: 'беспилотник',
  cruise: 'крылатый объект',
  ballistic: 'баллистический объект',
  missile: 'снаряд',
};

export const isMover = (k: string) => ['fighter', 'bomber', 'recon', 'support', 'uav', 'cruise', 'ballistic', 'air-missile', 'sam-missile'].includes(k);
export const isAircraft = (k: string) => ['fighter', 'bomber', 'recon', 'support', 'uav'].includes(k);
